/**
 * openweather API integration — auto-generated by learn.api, fixed by Émile
 * Source: https://openweathermap.org/api
 * Generated: 2026-02-08T00:28:20.018Z
 */
import { registerSkill } from "../loader.js";
import { log } from "../../utils/log.js";

const BASE_URL = "https://api.openweathermap.org/data/2.5";
const GEO_URL = "https://api.openweathermap.org/geo/1.0";
const ENV_VAR = "OPENWEATHER_API_KEY";

async function apiCall(endpoint: string, params: Record<string, string> = {}, base = BASE_URL): Promise<any> {
  const apiKey = process.env[ENV_VAR] || "";
  if (!apiKey) return { error: `${ENV_VAR} not configured in .env — use learn.credential to add it.` };

  const qs = new URLSearchParams({ ...params, appid: apiKey, units: "metric", lang: "fr" });
  const url = `${base}${endpoint}?${qs}`;

  try {
    log.debug(`[openweather] GET ${endpoint}`);
    const res = await fetch(url, { signal: AbortSignal.timeout(15000) });

    if (!res.ok) {
      const err = await res.text();
      log.warn(`[openweather] HTTP ${res.status}: ${err.slice(0, 200)}`);
      return { error: `HTTP ${res.status}: ${err.slice(0, 200)}` };
    }

    return res.json();
  } catch (err) {
    return { error: `Request failed: ${(err as Error).message}` };
  }
}

function formatWeather(data: any): string {
  if (data.error) return `Error: ${data.error}`;
  const temp = data.main?.temp ?? "?";
  const feels = data.main?.feels_like ?? "?";
  const desc = data.weather?.[0]?.description ?? "?";
  const humidity = data.main?.humidity ?? "?";
  const wind = data.wind?.speed ?? "?";
  const city = data.name ?? "?";
  const country = data.sys?.country ?? "";
  return `${city}${country ? `, ${country}` : ""}: ${temp}°C (ressenti ${feels}°C), ${desc}, humidité ${humidity}%, vent ${wind} m/s`;
}

registerSkill({
  name: "openweather.weather",
  description: "Get current weather for a city (temperature, conditions, humidity, wind).",
  adminOnly: false,
  argsSchema: {
    type: "object",
    properties: {
      city: { type: "string", description: "City name (e.g. 'Gatineau', 'Paris,FR', 'Ottawa,CA')" },
    },
    required: ["city"],
  },
  async execute(args): Promise<string> {
    const result = await apiCall("/weather", { q: String(args.city) });
    return formatWeather(result);
  },
});

registerSkill({
  name: "openweather.forecast",
  description: "Get 5-day weather forecast (3-hour intervals) for a city.",
  adminOnly: false,
  argsSchema: {
    type: "object",
    properties: {
      city: { type: "string", description: "City name" },
    },
    required: ["city"],
  },
  async execute(args): Promise<string> {
    const result = await apiCall("/forecast", { q: String(args.city) });
    if (result.error) return `Error: ${result.error}`;
    const items = (result.list || []).slice(0, 8); // Next 24h
    const lines = items.map((i: any) => {
      const dt = new Date(i.dt * 1000).toLocaleString("fr-CA", { timeZone: "America/Toronto", hour: "2-digit", minute: "2-digit", weekday: "short" });
      return `${dt}: ${i.main?.temp ?? "?"}°C, ${i.weather?.[0]?.description ?? "?"}`;
    });
    return `Prévisions ${result.city?.name || args.city} (24h):\n${lines.join("\n")}`;
  },
});

registerSkill({
  name: "openweather.air_pollution",
  description: "Get air quality index for coordinates.",
  adminOnly: false,
  argsSchema: {
    type: "object",
    properties: {
      lat: { type: "number", description: "Latitude" },
      lon: { type: "number", description: "Longitude" },
    },
    required: ["lat", "lon"],
  },
  async execute(args): Promise<string> {
    const result = await apiCall("/air_pollution", { lat: String(args.lat), lon: String(args.lon) });
    if (result.error) return `Error: ${result.error}`;
    const aqi = result.list?.[0]?.main?.aqi;
    const labels = ["", "Bon", "Acceptable", "Modéré", "Mauvais", "Très mauvais"];
    return `Qualité de l'air: ${labels[aqi] || "?"} (AQI: ${aqi}/5)`;
  },
});
